[ids]
*

[main]
# a = layer(control)
# s = layer(shift)
# d = layer(alt)
# f = layer(meta)
# h = layer(meta)
# j = layer(altgr)
# k = layer(shift)
# l = layer(control)
a = overloadt(meta, a, 200)
s = overloadt(control, s, 200)
d = overloadt(shift, d, 200)
f = overloadt(alt, f, 200)

h = overloadt(alt, h, 200)
j = overloadt(shift, j, 200)
k = overloadt(control, k, 200)
l = overloadt(meta, l, 200)

# ; = overloadt(control, ;, 200)
# v = overloadt(altgr, v, 200)
# m = overloadt(altgr, m, 200)
# leftshift = oneshot(shift)
# rightshift = oneshot(shift)


capslock = layer(pippo)


[pippo]
c = C-S-c
x = C-S-x
v = C-S-v

