[ids]
*

[main]
a = overloadt(meta, a, 200)
s = overloadt(control, s, 200)
d = overloadt(shift, d, 200)
f = overloadt(alt, f, 200)

h = overloadt(alt, h, 200)
j = overloadt(shift, j, 200)
k = overloadt(control, k, 200)
l = overloadt(meta, l, 200)   

capslock = layer(pippo)
# capslock = overloadt(pippo, macro(notification with battery status and date-time), 200)


[pippo]
a = leftmouse
s = rightmouse 

c = C-S-c
x = A-M-x
v = C-S-v
shift = layer(numpad)

k = volumeup
j = volumedown
up = volumeup
down = volumedown
space = playpause
z = suspend
backspace = delete
m = macro(miao enter)
h = macro(M-t 1000ms sudo space systemctl space hibernate space S-6 S-6 space e space enter)
p = macro(PZZNRC00A21D969Z)
t = macro(this too shall pass enter)

[numpad]
q = 7
w = 8
e = 9
a = 4
s = 5
d = 6
z = 1
x = 2
c = 3
r = 0

